FROM alpine:3.17
ARG NPM_REGISTRY
RUN apk update && apk add bash

WORKDIR /tmp

RUN wget https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
RUN tar -xf node-v18.12.1-linux-x64.tar.xz --directory=/usr/local --strip-components=1
RUN rm node-v18.12.1-linux-x64.tar.xz

RUN apk add npm

SHELL [ "/bin/bash", "-c" ]

WORKDIR /xui/common

COPY package.json package.json
COPY package-lock.json package-lock.json
copy webpackbase.config.js webpackbase.config.js
COPY lerna.json lerna.json
COPY README.md README.md
COPY packages packages

RUN node-v
RUN npm config set $NPM_REGISTRY
RUN npm install --legacy-peer-deps


CMD ["tail", "-f", "/dev/null"]
