FROM alpine:3.17

RUN apk update
RUN apk add bash

WORKDIR /tmp
RUN mkdir -p /.cache/yarn
RUN mkdir -p /.yarn
RUN wget https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
RUN tar -xf node-v18.12.1-linux-x64.tar.xz --directory=/usr/local --strip-components=1
RUN rm node-v18.12.1-linux-x64.tar.xz

RUN apk add npm
RUN npm install -g npm
RUN npm install -g yarn

SHELL [ "/bin/bash", "-c" ]

WORKDIR /xui/common

COPY package.json package.json
COPY package-lock.json package-lock.json
copy webpackbase.config.js webpackbase.config.js
COPY README.md README.md
COPY lerna.json lerna.json


RUN npm install --legacy-peer-deps

COPY packages packages

# Make a command to keep the container running when started.
CMD ["tail", "-f", "/dev/null"]
